// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generic-service.proto

// Protobuf Java Version: 3.25.1
package net.project.ecommerce.dependency.grpc.configuration;

public interface GrpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Any data = 1;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.google.protobuf.Any data = 1;</code>
   * @return The data.
   */
  com.google.protobuf.Any getData();
  /**
   * <code>.google.protobuf.Any data = 1;</code>
   */
  com.google.protobuf.AnyOrBuilder getDataOrBuilder();
}
