package net.project.ecommerce.dependency.api.enums;

public enum EnumUserActivityType {
	
	LOGIN, UPDATE_PROFILE, CHANGE_PASSWORD, 
	CREATION_USER, DELETE_USER, ADD_ADDRESS, 
	UPDATE_ADDRESS, DELETE_ADDRESS,
	ADD_PAYMENT_METHOD, UPDATE_PAYMENT_METHOD, DELETE_PAYMENT_METHOD

}
